name: Gtm

main: me.masonic.mc.Core

version: 1.4

commands:
  gtmatm:
    description: atm
    usage: /gtmatm
  gtmkit:
    description: gtmkit
    usage: /gtmkit
  gtmrank:
    description: gtmrank
    usage: /gtmrank
  gtmdr:
    description: gtmdr
    usage: /gtmdr
  gtmcp:
    description: gtmcp
    usage: /gtmcp
  gtmhouse:
    description: gtmhouse
    usage: /gtmhouse
  gtmtaxi:
    description: gtmtaxi
    usage: /gtmtaxi
  gtmsell:
    description: gtmsell
    usage: /gtmsell
  gtmvip:
    description: gtmvip
    usage: /gtmvip
  gtmcop:
    description: gtmcop
    usage: /gtmcop
  gtmpro:
    description: gtmpro
    usage: /gtmpro
permissions:
  gtm.rank.hobo:
    description: Access to all Hobo rank permissions
    children:
      essentials.tpaccept: true

      crackshot.use.glock17_a: true
      crackshot.use.usp45_a: true
      crackshot.use.glock42_a: true
      crackshot.use.acr_a: true
      crackshot.use.ak74m_a: true
      crackshot.use.FNSCAR_a: true
      crackshot.use.mp5_a: true
      crackshot.use.m4a4_a: true
      crackshot.use.rpk_a: true
      crackshot.use.m249_a: true
      crackshot.use.m134_a: true
      crackshot.use.s54_a: true
      crackshot.use.AWM_a: true
      -crackshot.use.all: true
      crackshot.use.grenade_a: true
      crackshot.use.putty_a: true
      crackshot.use.toaster_a: true
      backpack.1: true
      crackshot.use.morotov_a: true
      crackshot.use.gastear_a: true
      essentials.tpaccept: true
      deluxechat.utf: true
      treasurechest.access.treasure: true
      deluxetags.tag.hobo: true
      crackshot.use.melee1: true
      crackshot.use.melee2: true
      crackshot.use.melee5: true
  gtm.rank.criminal:
    description: Access to all Criminal rank permissions
    children:
      gangsplus.gang.*: true
      gangsplus.fight.*: true
      gangsplus.gangchat: true
      deluxetags.tag.criminal: true
  gtm.rank.thug:
    description: Access to all Thug rank permissions
    children:
      crackshot.use.Deagle_a: true
      deluxetags.tag.thug: true
  gtm.rank.gangster:
    description: Access to all Gangster rank permissions
    children:
      crackshot.use.qbz95_a: true
      deluxetags.tag.gangster: true
      gtm.modeaccess.cop: true
      crackshot.use.melee3: true
  gtm.rank.smuggler:
    description: Access to all Smuggler rank permissions
    children:
      crackshot.use.rpg7_a: true
      deluxetags.tag.smuggler: true
  gtm.rank.hunter:
    description: Access to all Hunter rank permissions
    children:
      crackshot.use.Barrett_a: true
      deluxetags.tag.hunter: true
      gtm.modeaccess.hitman: true
  gtm.rank.dealer:
    description: Access to all Dealer rank permissions
    children:
      crackshot.use.g36_a: true
      deluxetags.tag.dealer: true
  gtm.mode.cop:
    description: Access to all Cop Mode Specialized permissions
    children:
      deluxetags.tag.cop: true
      crackshot.use.stun_a: true
      crackshot.use.shield1: true