name: Gtm

main: me.masonic.mc.Core

version: 1.2

commands:
  gtmatm:
    description: atm
    usage: /gtmatm
  gtmkit:
    description: gtmkit
    usage: /gtmkit
  gtmrank:
    description: gtmrank
    usage: /gtmrank
  gtmdr:
    description: gtmdr
    usage: /gtmdr
  gtmcp:
    description: gtmcp
    usage: /gtmcp
  gtmhouse:
    description: gtmhouse
    usage: /gtmhouse
  gtmtaxi:
    description: gtmtaxi
    usage: /gtmtaxi
  gtmsell:
    description: gtmsell
    usage: /gtmsell
  gtmvip:
    description: gtmvip
    usage: /gtmvip
permissions:
  gtm.rank.criminal:
    description: Access to all Criminal rank permissions
    children:
      gangsplus.gang.*: true
      gangsplus.fight.*: true
      gangsplus.gangchat: true
      deluxetags.tag.criminal: true
  gtm.rank.thug:
    description: Access to all Thug rank permissions
    children:
      crackshot.use.Deagle_a: true
      deluxetags.tag.thug: true
  gtm.rank.gangster:
    description: Access to all Gangster rank permissions
    children:
      crackshot.use.qbz95_a: true
      deluxetags.tag.gangster: true
  gtm.rank.smuggler:
    description: Access to all Smuggler rank permissions
    children:
      crackshot.use.rpg7_a: true
      deluxetags.tag.smuggler: true
  gtm.rank.hunter:
    description: Access to all Hunter rank permissions
    children:
      crackshot.use.Barrett_a: true
      deluxetags.tag.hunter: true
  gtm.rank.dealer:
    description: Access to all Dealer rank permissions
    children:
      crackshot.use.g36_a: true
      deluxetags.tag.dealer: true